version: "3.8"

services:
  backend:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hotelbooking
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
